### ISSUE TITLE
Front End interacts with the user via HTTP and communicates with Messaging via a messaging library.

### ISSUE THREAD

**Issue by tas56** [ak2254/IT490-groupproject#17]

**Comment by krb39** [comment]
There is an circular import in front-end which needs to be identified, still debugging.

**Comment by krb39** [comment]
Commenting for more debugging purpose:

from ..security import gen_salt

ImportError: cannot import name 'gen_salt' from partially initialized module 'werkzeug.security' (most likely due to a circular import) (/usr/local/lib/python3.9/site-packages/werkzeug/security.py)
